/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Escuderia;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author David
 */
public class JframePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JframePrincipal
     */
    public static Escuderia escuderia;
    PanelInicial panelInicial = new PanelInicial();
    PanelEntrar panelEntrar;
    PanelBienvenida panelBienvenida;
    JDialogAutor jDialogAutor;
    PanelFilasUnaUna panelFilasUnaUna;
    PanelPerfil panelPerfil;
    public JframePrincipal() {
        initComponents();

        itemSalir.setEnabled(false);
        menuModificaciones.setEnabled(false);
        menuAcercaDe.setEnabled(false);
        
        panelEntrar = new PanelEntrar(this);
        
        this.setResizable(false);
        this.setLayout(new BorderLayout());
        cambiarPanel(panelInicial);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuAcceso = new javax.swing.JMenu();
        itemEntrar = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        menuModificaciones = new javax.swing.JMenu();
        verFilasUnaUna = new javax.swing.JMenuItem();
        verPerfil = new javax.swing.JMenuItem();
        menuAcercaDe = new javax.swing.JMenu();
        itemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuAcceso.setText("Acceso");

        itemEntrar.setText("Entrar");
        itemEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEntrarActionPerformed(evt);
            }
        });
        menuAcceso.add(itemEntrar);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuAcceso.add(itemSalir);

        jMenuBar1.add(menuAcceso);

        menuModificaciones.setText("Modificaciones");

        verFilasUnaUna.setText("Ver filas una a una");
        verFilasUnaUna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verFilasUnaUnaActionPerformed(evt);
            }
        });
        menuModificaciones.add(verFilasUnaUna);

        verPerfil.setText("Ver perfil");
        verPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPerfilActionPerformed(evt);
            }
        });
        menuModificaciones.add(verPerfil);

        jMenuBar1.add(menuModificaciones);

        menuAcercaDe.setText("Acerca de");

        itemAcercaDe.setText("Acerca de");
        itemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaDeActionPerformed(evt);
            }
        });
        menuAcercaDe.add(itemAcercaDe);

        jMenuBar1.add(menuAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEntrarActionPerformed
        panelInicial.setVisible(false);
        
        panelEntrar = new PanelEntrar(this);
       this.cambiarPanel(panelEntrar);
       
    }//GEN-LAST:event_itemEntrarActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        itemEntrar.setEnabled(true);
        itemSalir.setEnabled(false);
        menuModificaciones.setEnabled(false);
        menuAcercaDe.setEnabled(false);
        
        panelBienvenida.setVisible(false);
        
        panelInicial = new PanelInicial();
        this.cambiarPanel(panelInicial);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaDeActionPerformed
        jDialogAutor = new JDialogAutor(this, true);
        jDialogAutor.setVisible(true);
        this.pack();
    }//GEN-LAST:event_itemAcercaDeActionPerformed

    private void verFilasUnaUnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verFilasUnaUnaActionPerformed
        
        try {
            panelFilasUnaUna = new PanelFilasUnaUna(this);
        } catch (SQLException ex) {
            Logger.getLogger(JframePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.cambiarPanel(panelFilasUnaUna);
        
    }//GEN-LAST:event_verFilasUnaUnaActionPerformed

    private void verPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPerfilActionPerformed
        panelPerfil = new PanelPerfil(this, escuderia);
        
        this.cambiarPanel(panelPerfil);
    }//GEN-LAST:event_verPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAcercaDe;
    private javax.swing.JMenuItem itemEntrar;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAcceso;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenu menuModificaciones;
    private javax.swing.JMenuItem verFilasUnaUna;
    private javax.swing.JMenuItem verPerfil;
    // End of variables declaration//GEN-END:variables

    void cambiarPanel(javax.swing.JPanel panel) 
    {
        // Eliminar todos los componentes existentes en el marco
        this.getContentPane().removeAll();

        // Establecer el nuevo panel en el contenido del marco
        this.setContentPane(panel);

        // Revalidar y repintar el marco para reflejar los cambios
        this.revalidate();
        this.repaint();

        // Ajustar el tamaño del marco según el nuevo panel
        this.pack();
    }

    public JDialogAutor getjDialogAutor() {
        return jDialogAutor;
    }

    public void setjDialogAutor(JDialogAutor jDialogAutor) {
        this.jDialogAutor = jDialogAutor;
    }

    public JMenuItem getItemAcercaDe() {
        return itemAcercaDe;
    }

    public void setItemAcercaDe(JMenuItem itemAcercaDe) {
        this.itemAcercaDe = itemAcercaDe;
    }

    public JMenu getMenuAcercaDe() {
        return menuAcercaDe;
    }

    public void setMenuAcercaDe(JMenu menuAcercaDe) {
        this.menuAcercaDe = menuAcercaDe;
    }

    
    public static Escuderia getEscuderia() {
        return escuderia;
    }

    public static void setEscuderia(Escuderia escuderia) {
        JframePrincipal.escuderia = escuderia;
    }

    public PanelInicial getPanelInicial() {
        return panelInicial;
    }

    public void setPanelInicial(PanelInicial panelInicial) {
        this.panelInicial = panelInicial;
    }

    public PanelEntrar getPanelEntrar() {
        return panelEntrar;
    }

    public void setPanelEntrar(PanelEntrar panelEntrar) {
        this.panelEntrar = panelEntrar;
    }

    public PanelBienvenida getPanelBienvenida() {
        return panelBienvenida;
    }

    public void setPanelBienvenida(PanelBienvenida panelBienvenida) {
        this.panelBienvenida = panelBienvenida;
    }

    public JMenuItem getItem1() {
        return verFilasUnaUna;
    }

    public void setItem1(JMenuItem item1) {
        this.verFilasUnaUna = item1;
    }


    public JMenuItem getItem3() {
        return verPerfil;
    }

    public void setItem3(JMenuItem item3) {
        this.verPerfil = item3;
    }


    public JMenuItem getItemEntrar() {
        return itemEntrar;
    }

    public void setItemEntrar(JMenuItem itemEntrar) {
        this.itemEntrar = itemEntrar;
    }

    public JMenuItem getItemSalir() {
        return itemSalir;
    }

    public void setItemSalir(JMenuItem itemSalir) {
        this.itemSalir = itemSalir;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenu getMenuAcceso() {
        return menuAcceso;
    }

    public void setMenuAcceso(JMenu menuAcceso) {
        this.menuAcceso = menuAcceso;
    }

    public JMenu getMenuModificaciones() {
        return menuModificaciones;
    }

    public void setMenuModificaciones(JMenu menuModificaciones) {
        this.menuModificaciones = menuModificaciones;
    }
    
    
}
