/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConsultaEscuderia;
import Controlador.MError;
import Controlador.MiExcepcion;
import Modelo.Escuderia;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author David
 */
public class PanelPerfil extends javax.swing.JPanel {

    JFrame JframePrincipal;
    Escuderia escuderia;
    
    public PanelPerfil(JFrame JframePrincipal, Escuderia escuderia) {
        initComponents();
        
        this.JframePrincipal = JframePrincipal;
        this.escuderia = escuderia;
        
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPerfil = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblMundiales = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtMundiales = new javax.swing.JTextField();
        btnAniadirMundial = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(708, 580));

        lblPerfil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPerfil.setForeground(new java.awt.Color(255, 0, 0));
        lblPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPerfil.setText("VER PERFIL");

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 0, 0));
        lblNombre.setText("Nombre:");

        lblContraseña.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 0, 0));
        lblContraseña.setText("Contraseña:");

        lblCodigo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 0, 0));
        lblCodigo.setText("Código:");

        lblMundiales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMundiales.setForeground(new java.awt.Color(255, 0, 0));
        lblMundiales.setText("Mundiales:");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtContrasenia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtMundiales.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAniadirMundial.setBackground(new java.awt.Color(255, 0, 0));
        btnAniadirMundial.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAniadirMundial.setForeground(new java.awt.Color(255, 255, 255));
        btnAniadirMundial.setText("Añadir Mundial");
        btnAniadirMundial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirMundialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblContraseña)
                            .addComponent(lblCodigo)
                            .addComponent(lblMundiales))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtContrasenia)
                            .addComponent(txtCodigo)
                            .addComponent(txtMundiales, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addComponent(btnAniadirMundial)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMundiales)
                    .addComponent(txtMundiales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAniadirMundial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAniadirMundialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirMundialActionPerformed
          
        
        try {
            ConsultaEscuderia.actualizarMundiales(escuderia, escuderia.getCodigo());
            txtMundiales.setText("" + (escuderia.getMundiales()+1));
        } catch (SQLException ex) {
            Logger.getLogger(PanelPerfil.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MiExcepcion ex) {
            JOptionPane.showMessageDialog(this, MError.getMensaje(ex.getCodigo()));
            MError.CreadorLog(MError.getMensaje(ex.getCodigo()));
        }
            
        
    }//GEN-LAST:event_btnAniadirMundialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadirMundial;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblMundiales;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtMundiales;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void mostrarDatos()
    {
        txtNombre.setText(escuderia.getNombre());
        txtContrasenia.setText(escuderia.getContraseña());
        txtCodigo.setText("" + escuderia.getCodigo());
        txtMundiales.setText("" + escuderia.getMundiales());
    }
    
    
    
}
