/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConsultaEscuderia;
import Controlador.MError;
import Controlador.MiExcepcion;
import Modelo.Escuderia;
import Modelo.Patrocinador;
import Modelo.Piloto;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class PanelJtable extends javax.swing.JPanel {

    PanelFilasUnaUna panelFilasUnaUna;
    
    JframePrincipal JframePrincipal;
    
    Piloto piloto;
    
    ArrayList<Patrocinador> listaPatrocinadores = new ArrayList<Patrocinador>();
    
    
    public PanelJtable(JframePrincipal JframePrincipal, Piloto piloto) throws SQLException {
        initComponents();
        this.JframePrincipal = JframePrincipal;
        this.piloto = piloto;
        
        listaPatrocinadores = ConsultaEscuderia.listaPatrocinadores(piloto.getNif());
        
        actualizarTabla(listaPatrocinadores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        lblPiloto = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnAniadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable.setForeground(new java.awt.Color(255, 0, 0));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        lblPiloto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPiloto.setForeground(new java.awt.Color(255, 0, 0));
        lblPiloto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 0, 0));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnAniadir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAniadir.setForeground(new java.awt.Color(255, 0, 0));
        btnAniadir.setText("Añadir");
        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 0, 0));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)
                        .addGap(75, 75, 75)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAniadir)
                    .addComponent(btnBorrar)
                    .addComponent(btnVolver)
                    .addComponent(btnModificar))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        try {
            panelFilasUnaUna = new PanelFilasUnaUna(JframePrincipal);
        } catch (SQLException ex) {
            Logger.getLogger(PanelJtable.class.getName()).log(Level.SEVERE, null, ex);
        }
        JframePrincipal.cambiarPanel(panelFilasUnaUna);
        JframePrincipal.pack();
        
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
         int filaSeleccionada = jTable.getSelectedRow();

    if (filaSeleccionada >= 0) {
        int codigoPatrocinador = (int) jTable.getValueAt(filaSeleccionada, 0);

        try {
            ConsultaEscuderia.eliminarPatrocinador(codigoPatrocinador);
            
            // Actualizar la tabla después de eliminar el patrocinador
            listaPatrocinadores = ConsultaEscuderia.listaPatrocinadores(piloto.getNif());
            actualizarTabla(listaPatrocinadores);
        } catch (SQLException ex) {
            Logger.getLogger(PanelJtable.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        // Muestra un mensaje indicando que no se ha seleccionado ninguna fila
        // Puedes utilizar JOptionPane u otro mecanismo para mostrar mensajes
        JOptionPane.showMessageDialog(this, "Selecciona un patrocinador antes de pulsar el boton");
    }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed
        mostrarDialogoNuevoPatrocinador();
    }//GEN-LAST:event_btnAniadirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       mostrarDialogoModificarPatrocinador();
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnModificar;
    public javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel lblPiloto;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblPiloto() {
        return lblPiloto;
    }

    public void setLblPiloto(JLabel lblPiloto) {
        this.lblPiloto = lblPiloto;
    }

    public void actualizarTabla(ArrayList<Patrocinador> patrocinadores) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Codigo");
        model.addColumn("Nombre del patrocinador");
        model.addColumn("Nif del piloto");

        for (Patrocinador patrocinador : patrocinadores) {
            model.addRow(new Object[]{patrocinador.getCodigo(), patrocinador.getNombre(), patrocinador.getPilNif()});
        }

        jTable.setModel(model);
    }

    private void mostrarDialogoNuevoPatrocinador() {
        JPanel panel = new JPanel(new GridLayout(3, 2));

        JTextField txtCodigo = new JTextField();
        JTextField txtNombre = new JTextField();
        JTextField txtNifPiloto = new JTextField();
        

        panel.add(new JLabel("Codigo: "));
        panel.add(txtCodigo);
        panel.add(new JLabel("Nombre del Patrocinador:"));
        panel.add(txtNombre);
        panel.add(new JLabel("NIF del Piloto:"));
        panel.add(txtNifPiloto);
        txtNifPiloto.setText(piloto.getNif());
        txtNifPiloto.setEnabled(false);

        int resultado = JOptionPane.showConfirmDialog(
                this,
                panel,
                "Añadir Nuevo Patrocinador",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (resultado == JOptionPane.OK_OPTION) {
            // Obtén los datos ingresados
            int codigo = Integer.parseInt(txtCodigo.getText());
            String nombrePatrocinador = txtNombre.getText();
            String nif = piloto.getNif();
            

                Patrocinador nuevoPatrocinador = new Patrocinador(codigo, nombrePatrocinador, nif);
                nuevoPatrocinador.setCodigo(codigo);
                nuevoPatrocinador.setNombre(nombrePatrocinador);
                nuevoPatrocinador.setPilNif(nif);
                
                try {
                
                
                try {
                    // Llama al método para insertar el nuevo patrocinador
                    ConsultaEscuderia.insertarPatrocinador(nuevoPatrocinador);
                } catch (MiExcepcion ex) {
                    JOptionPane.showMessageDialog(this, MError.getMensaje(ex.getCodigo()));
                    MError.CreadorLog(MError.getMensaje(ex.getCodigo()));
                }

                // Actualiza la tabla con la nueva lista de patrocinadores
                listaPatrocinadores = ConsultaEscuderia.listaPatrocinadores(piloto.getNif());
                actualizarTabla(listaPatrocinadores);
            } catch (SQLException ex) {
                // Maneja la excepción según tus necesidades
                ex.printStackTrace();
            }
        }
            
    }
    
    private void mostrarDialogoModificarPatrocinador() {
    int selectedRow = jTable.getSelectedRow();

    if (selectedRow != -1) {
        Patrocinador patrocinadorSeleccionado = listaPatrocinadores.get(selectedRow);
        Patrocinador patrocinador = listaPatrocinadores.get(selectedRow);
        
        JTextField txtCodigo = new JTextField(String.valueOf(patrocinadorSeleccionado.getCodigo()));
        JTextField txtNombre = new JTextField(patrocinadorSeleccionado.getNombre());
        JTextField txtNif = new JTextField(patrocinadorSeleccionado.getPilNif());
        txtNif.setEnabled(false);

        Object[] message = {
            "Codigo:", txtCodigo,
            "Nombre:", txtNombre,
            "NIF del piloto:", txtNif
        };

        int option = JOptionPane.showConfirmDialog(null, message, "Modificar Patrocinador", JOptionPane.OK_CANCEL_OPTION);

        if (option == JOptionPane.OK_OPTION) {
            try {
                int nuevoCodigo = Integer.parseInt(txtCodigo.getText());
                String nuevoNombre = txtNombre.getText();
                String nuevoNif = txtNif.getText();

                // Actualizar el patrocinador en la lista
                patrocinadorSeleccionado.setCodigo(nuevoCodigo);
                patrocinadorSeleccionado.setNombre(nuevoNombre);

                // Actualizar el patrocinador en la base de datos
                ConsultaEscuderia.actualizarPatrocinador(patrocinadorSeleccionado, patrocinador.getCodigo());

                // Actualizar la tabla en el JPanel
                actualizarTabla(listaPatrocinadores);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Error: El código debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                // Manejar la excepción según tu lógica
                ex.printStackTrace();
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione un patrocinador para modificar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
}

    
}
