/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConsultaEscuderia;
import Controlador.ControladorArrayList;
import Modelo.Escuderia;
import Modelo.Piloto;
import java.awt.BorderLayout;
import java.awt.Image;
import java.io.File;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author David
 */
public class PanelFilasUnaUna extends javax.swing.JPanel {

    /**
     * Creates new form PanelFilasUnaUna
     */
    
    Piloto seleccion;
    
    final Piloto[] pilotoSeleccionado = new Piloto[1];
    
    JframePrincipal JframePrincipal;
    
    PanelBienvenida panelBienvenida = new PanelBienvenida();
    
    PanelJtable panelJtable;
    
    ArrayList<Piloto> pilotos = new ArrayList<>();
    
    public PanelFilasUnaUna(JframePrincipal frame) throws SQLException {
        initComponents();
        
        this.JframePrincipal = frame;
        jList.setModel(modelListPiloto(ConsultaEscuderia.listaPilotos(JframePrincipal.escuderia.getCodigo())));
        
        
        
        pilotos = ConsultaEscuderia.listaPilotos(JframePrincipal.escuderia.getCodigo());
        
        if (!pilotos.isEmpty()) {
            jList.setSelectedIndex(0);
            mostrarDetallesPiloto(pilotos.get(0)); // Muestra los detalles del primer piloto
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrimero = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        lblNif = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblFechaNac = new javax.swing.JLabel();
        lblSueldo = new javax.swing.JLabel();
        txtNif = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        btnRetroceder = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnPatrocinadores = new javax.swing.JButton();
        btnSeleccionarImagen = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnPrimero.setBackground(new java.awt.Color(255, 0, 0));
        btnPrimero.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPrimero.setForeground(new java.awt.Color(255, 255, 255));
        btnPrimero.setText("Primero");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnUltimo.setBackground(new java.awt.Color(255, 0, 0));
        btnUltimo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnUltimo.setForeground(new java.awt.Color(255, 255, 255));
        btnUltimo.setText("Último");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList);

        lblNif.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNif.setForeground(new java.awt.Color(255, 0, 0));
        lblNif.setText("NIF:");

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 0, 0));
        lblNombre.setText("Nombre:");

        lblFechaNac.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFechaNac.setForeground(new java.awt.Color(255, 0, 0));
        lblFechaNac.setText("Fecha:");

        lblSueldo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSueldo.setForeground(new java.awt.Color(255, 0, 0));
        lblSueldo.setText("Sueldo:");

        txtNif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSueldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnRetroceder.setBackground(new java.awt.Color(255, 0, 0));
        btnRetroceder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRetroceder.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.setText("<--");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });

        btnAvanzar.setBackground(new java.awt.Color(255, 0, 0));
        btnAvanzar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAvanzar.setForeground(new java.awt.Color(255, 255, 255));
        btnAvanzar.setText("-->");
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(255, 0, 0));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnPatrocinadores.setBackground(new java.awt.Color(255, 0, 0));
        btnPatrocinadores.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPatrocinadores.setForeground(new java.awt.Color(255, 255, 255));
        btnPatrocinadores.setText("Patrocinadores");
        btnPatrocinadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatrocinadoresActionPerformed(evt);
            }
        });

        btnSeleccionarImagen.setBackground(new java.awt.Color(255, 0, 0));
        btnSeleccionarImagen.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSeleccionarImagen.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarImagen.setText("Seleccionar Imagen");
        btnSeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNif)
                                    .addComponent(lblNombre)
                                    .addComponent(lblFechaNac)
                                    .addComponent(lblSueldo))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNif)
                                    .addComponent(txtNombre)
                                    .addComponent(txtFecha)
                                    .addComponent(txtSueldo, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnPrimero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRetroceder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAvanzar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(121, 121, 121)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPatrocinadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSeleccionarImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNif)
                            .addComponent(txtNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaNac)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSueldo)
                            .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAvanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPrimero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVolver)
                            .addComponent(btnPatrocinadores))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        JframePrincipal.setContentPane(panelBienvenida);
        JframePrincipal.pack();
        Escuderia e1 = JframePrincipal.getEscuderia();
        panelBienvenida.lblBienvenido.setText("Bienvenido, director de "+e1.getNombre());
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListValueChanged
        int index = jList.getSelectedIndex();
        
        Piloto p1 = pilotos.get(index);
        mostrarDetallesPiloto(p1);
    }//GEN-LAST:event_jListValueChanged

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        int index = new ControladorArrayList().avanzaIndex(jList, this);
        jList.setSelectedIndex(index);
        Piloto p1 = pilotos.get(index);
        mostrarDetallesPiloto(p1);
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        int index = new ControladorArrayList().retrocedeIndex(jList, this);
        jList.setSelectedIndex(index);
        Piloto p1 = pilotos.get(index);
        mostrarDetallesPiloto(p1);
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        int index = new ControladorArrayList().irPrimeroIndex(jList, this);
        
        jList.setSelectedIndex(index);
        Piloto p1 = pilotos.get(index);
        mostrarDetallesPiloto(p1);
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        int index = new ControladorArrayList().irUltimoIndex(jList, this);
        
        jList.setSelectedIndex(index);
        Piloto p1 = pilotos.get(index);
        mostrarDetallesPiloto(p1);
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnPatrocinadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatrocinadoresActionPerformed
        int index = jList.getSelectedIndex();
        Piloto p1 = pilotos.get(index);
        
        try {
            panelJtable = new PanelJtable(JframePrincipal, p1);
        } catch (SQLException ex) {
            Logger.getLogger(PanelFilasUnaUna.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JframePrincipal.cambiarPanel(panelJtable);
        
        
        panelJtable.getLblPiloto().setText("Patrocinadores de "+p1.getNombre());
    }//GEN-LAST:event_btnPatrocinadoresActionPerformed

    private void btnSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImagenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos de imagen", "jpg", "jpeg", "png", "gif"));

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try {
                // Obtener la nueva ruta de la imagen
                String nuevaRuta = selectedFile.getAbsolutePath();

                // Actualizar la interfaz de usuario con la nueva imagen
                mostrarImagen(selectedFile);
                int index = jList.getSelectedIndex();
        
                Piloto p1 = pilotos.get(index);
                p1.setFoto(nuevaRuta);

                // Actualizar la ruta de la imagen en la base de datos
                String nifPilotoSeleccionado = pilotos.get(jList.getSelectedIndex()).getNif();
                ConsultaEscuderia.actualizarImagenPiloto(nifPilotoSeleccionado, nuevaRuta);
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al actualizar la imagen en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSeleccionarImagenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnPatrocinadores;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JButton btnSeleccionarImagen;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNif;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSueldo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNif;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
    
    
    private DefaultListModel modelListPiloto(ArrayList<Piloto> pilotos) throws SQLException{
        DefaultListModel model = new DefaultListModel<>();
            for(Piloto p1 : pilotos){
                model.addElement(p1);
            }
    return model;
    }
    
    private void mostrarDetallesPiloto(Piloto piloto) {
        // Muestra los detalles del piloto en los campos de texto u otros componentes
        txtNif.setText(piloto.getNif());
        txtNombre.setText(piloto.getNombre());
        txtFecha.setText(""+piloto.getFechaNacimiento());
        txtSueldo.setText(String.valueOf(piloto.getSueldo()));
     
        String rutaFoto = piloto.getFoto();
        ImageIcon imagen = new ImageIcon(rutaFoto);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(145, 181, Image.SCALE_DEFAULT));
        lblFoto.setIcon(icono);
        this.repaint();
    }
    
   private void mostrarImagen(File file) {
        ImageIcon icon = new ImageIcon(file.getAbsolutePath());
        Image image = icon.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_SMOOTH);
        lblFoto.setIcon(new ImageIcon(image));
    } 
}
